package com.maya2002yagan.weatherapp.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * This data class stores the weather info for the next 7 days. This class was needed in order to
 * store the weather info in the local database day by day. Previously, we did this with the class
 * DailyWeather but the data was stored as a single list in each field, which is unwanted behavior.
 * This class has the same fields as DailyWeather
 *
 * @param id The unique identifier for the weather entry. Automatically generated by Room.
 * @param time The date and time of the weather forecast.
 * @param weather_code The weather condition code.
 * @param temperature_2m_max The maximum temperature at 2 meters above ground level.
 * @param temperature_2m_min The minimum temperature at 2 meters above ground level.
 * @param uv_index_clear_sky_max The maximum UV index under clear sky conditions.
 * @param rain_sum The total amount of rainfall.
 * @param precipitation_probability_max The maximum probability of precipitation.
 * @param wind_speed_10m_max The maximum wind speed at 10 meters above ground level.
 */
@Entity(tableName = "DailyWeather")
data class SingleDailyWeather(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    @ColumnInfo(name = "time")
    val time: String,
    @ColumnInfo(name = "weather_code")
    val weather_code: Int,
    @ColumnInfo(name = "temperature_2m_max")
    val temperature_2m_max: Double,
    @ColumnInfo(name = "temperature_2m_min")
    val temperature_2m_min: Double,
    @ColumnInfo(name = "uv_index_clear_sky_max")
    val uv_index_clear_sky_max: Double,
    @ColumnInfo(name = "rain_sum")
    val rain_sum: Double,
    @ColumnInfo(name = "precipitation_probability_max")
    val precipitation_probability_max: Int,
    @ColumnInfo(name = "wind_speed_10m_max")
    val wind_speed_10m_max: Double,
)
